spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_URL_DOCKER:localhost:13306}/mall_oauth2?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 14yhl9t
#    druid:
#      properties:
#        driverClassName: com.mysql.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8
#        username: root
#        password: root
#        filters: stat,wall
#      stat-servlet:
#        url-mapping: /druid/*
