server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:${SPRING_CONFIG_DIR:${HOME}/.millimall/config-server-files}
    consul:
      host: ${CONSUL_HOST_DOCKER:localhost}
      port: ${CONSUL_PORT_DOCKER:8500}
  rabbitmq:
    host: ${RABBITMQ_HOST_DOCKER:localhost}
    port: ${RABBITMQ_PORT_DOCKER:5672}
management:
  security:
    enabled: false