server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: ${SPRING_CONFIG_DIR:${HOME}/.millimall/config-server-files}
    consul:
      port: 8500
      host: localhost
management:
  security:
    enabled: false