server:
  port: 9898

zuul:
  ignoredServices: '*'
  routes:
    goods:
      sensitiveHeaders:
      path: /goods/**
      url: http://localhost:8080
    oauth2:
      sensitiveHeaders:
      path: /sso/**
      url: http://localhost:9999/sso

spring:
  application:
    name: admin-gateway
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
      host: localhost
      port: 8500
