server:
  port: 11088
spring:
  application:
    name: mall-thrift-server
  cloud:
    consul:
      host: localhost
      port: 8500
  zipkin:
    enabled: false
#eureka:
#  client:
#    service-url:
#      defaultZone: http://peer2:1112/eureka/