server:
  port: 9999
  context-path: /sso

spring:
  application:
    name: oauth2-server
  datasource:
    name: oauth2-db
    url: jdbc:mysql://localhost:3306/mall-oauth2?verifyServerCertificate=false&useSSL=false&characterEncoding=UTF-8
    username: root
    password: root
  output:
    ansi:
      enabled: detect
  redis:
    host: localhost
    port: 32768

security:
  oauth2:
    authorization:
      check-token-access: isAuthenticated()

logging:
  level:
    org.springframework.security: DEBUG
