server:
  port: 9898

zuul:
  ignoredServices: '*'
  routes:
    goods:
      path: /goods/**
      serviceId: goods-restful-api
    oauth2:
      path: /sso/**
      serviceId: oauth2-server
      stripPrefix: false

spring:
  application:
    name: admin-gateway
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
#        enabled: false
      host: localhost
      port: 8500

security:
  sessions: always
#  basic:
#    enabled: false
  oauth2:
    client:
      accessTokenUri: http://${OAUTH2_SERVER_DOCKER:'localhost:9999'}/sso/oauth/token
      userAuthorizationUri: http://${OAUTH2_SERVER_DOCKER:'localhost:9999'}/sso/oauth/authorize
      clientId: mall-admin-gateway-client
      clientSecret: 123456
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
          -----END PUBLIC KEY-----
  ignored: /health, /sso/**